export const ROUTES = {
  LOGIN: "/login",
  CALENDARIO: "/calendario",
  DASHBOARD: "/dashboard",
  VIAJES: "/viajes",
  RESERVAS: "/reservas",
  ENCOMIENDAS: "/encomiendas",
  HORARIOS: "/horarios",
  RUTAS: "/rutas",
  PAISES: "/paises",
  PASAJEROS: "/pasajeros",
  PROVEEDORES: "/proveedores",
  TRIPULACION: "/tripulacion",
  ESTADOS_VIAJE: "/estados-viaje",
  MANIFIESTOS: "/manifiestos",
  SUCURSALES: "/sucursales",
  USUARIOS: "/usuarios",
} as const;
